In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable

In [2]:
import numpy as np

In [3]:
vocab = ["var","this","function","public","namespace","using","System","public", "enum", "Function", "Module"];
y_labels = [".cs", ".js", ".vb"]

In [4]:
texts = []

txt1 = "namespace public enum namespace System String"
txt2 = "this var function var this"
txt3 = "Function Module Module"

texts.append(txt1)
texts.append(txt2)
texts.append(txt3)

labels = np.array([0, 1, 2], np.long)

In [5]:
texts

['namespace public enum namespace System String',
 'this var function var this',
 'Function Module Module']

In [59]:
xs = []
for txt in texts:
    xarr = np.zeros(len(vocab))
    for item in txt.split():
        # get index
        xarr[vocab.index(item)] += 1
    xs.append(xarr)
    

In [60]:
xs

[array([0., 0., 0., 1., 2., 0., 1., 0., 1., 0., 0.]),
 array([2., 2., 1., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2.])]

In [62]:
xstensor = torch.Tensor(xs)

In [86]:
ystensor = torch.LongTensor(labels)

In [85]:
xstensor, ystensor

(tensor([[0., 0., 0., 1., 2., 0., 1., 0., 1., 0., 0.],
         [2., 2., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 2.]]), tensor([0., 1., 2.]))

In [79]:
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.L1 = torch.nn.Linear(len(vocab), 24)
        self.L2 = torch.nn.Linear(24, 12)
        self.L3 = torch.nn.Linear(12, len(labels))
        
    def forward(self, x):
        x = F.relu(self.L1(x))
        x = F.relu(self.L2(x))

        y_pred = self.L3(x)
        return y_pred    


model = Net()

In [80]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=.5)

In [87]:
ystensor

tensor([0, 1, 2])

In [99]:
for epoch in range(500):
    # forward pass
    y_pred = model(xstensor)
    optimizer.zero_grad()

    loss = criterion(y_pred, ystensor)
    print(loss)
    loss.backward()
    optimizer.step()

tensor(1.1211, grad_fn=<NllLossBackward>)
tensor(1.1177, grad_fn=<NllLossBackward>)
tensor(1.1143, grad_fn=<NllLossBackward>)
tensor(1.1110, grad_fn=<NllLossBackward>)
tensor(1.1076, grad_fn=<NllLossBackward>)
tensor(1.1048, grad_fn=<NllLossBackward>)
tensor(1.1023, grad_fn=<NllLossBackward>)
tensor(1.0998, grad_fn=<NllLossBackward>)
tensor(1.0972, grad_fn=<NllLossBackward>)
tensor(1.0948, grad_fn=<NllLossBackward>)
tensor(1.0923, grad_fn=<NllLossBackward>)
tensor(1.0898, grad_fn=<NllLossBackward>)
tensor(1.0874, grad_fn=<NllLossBackward>)
tensor(1.0850, grad_fn=<NllLossBackward>)
tensor(1.0826, grad_fn=<NllLossBackward>)
tensor(1.0805, grad_fn=<NllLossBackward>)
tensor(1.0784, grad_fn=<NllLossBackward>)
tensor(1.0764, grad_fn=<NllLossBackward>)
tensor(1.0743, grad_fn=<NllLossBackward>)
tensor(1.0722, grad_fn=<NllLossBackward>)
tensor(1.0701, grad_fn=<NllLossBackward>)
tensor(1.0681, grad_fn=<NllLossBackward>)
tensor(1.0660, grad_fn=<NllLossBackward>)
tensor(1.0639, grad_fn=<NllLossBac

tensor(0.1991, grad_fn=<NllLossBackward>)
tensor(0.1960, grad_fn=<NllLossBackward>)
tensor(0.1928, grad_fn=<NllLossBackward>)
tensor(0.1897, grad_fn=<NllLossBackward>)
tensor(0.1867, grad_fn=<NllLossBackward>)
tensor(0.1836, grad_fn=<NllLossBackward>)
tensor(0.1807, grad_fn=<NllLossBackward>)
tensor(0.1778, grad_fn=<NllLossBackward>)
tensor(0.1748, grad_fn=<NllLossBackward>)
tensor(0.1719, grad_fn=<NllLossBackward>)
tensor(0.1692, grad_fn=<NllLossBackward>)
tensor(0.1664, grad_fn=<NllLossBackward>)
tensor(0.1637, grad_fn=<NllLossBackward>)
tensor(0.1611, grad_fn=<NllLossBackward>)
tensor(0.1584, grad_fn=<NllLossBackward>)
tensor(0.1558, grad_fn=<NllLossBackward>)
tensor(0.1533, grad_fn=<NllLossBackward>)
tensor(0.1508, grad_fn=<NllLossBackward>)
tensor(0.1483, grad_fn=<NllLossBackward>)
tensor(0.1460, grad_fn=<NllLossBackward>)
tensor(0.1437, grad_fn=<NllLossBackward>)
tensor(0.1414, grad_fn=<NllLossBackward>)
tensor(0.1392, grad_fn=<NllLossBackward>)
tensor(0.1370, grad_fn=<NllLossBac

In [112]:
output = model(xstensor[2])

In [105]:
xstensor[0]

tensor([0., 0., 0., 1., 2., 0., 1., 0., 1., 0., 0.])

In [113]:
output.data.max(0, keepdim=True)[1]

tensor([2])

In [161]:
newtexts = []
new1 = "public enum namespace System namespace namespace System"
newtexts.append(new1)
new2 = "Function Module"
newtexts.append(new2)
new3 = "this var System public enum"
newtexts.append(new3)

newlabels = np.array([0], np.long)

newxs = []
for txt in newtexts:
    xarr = np.zeros(len(vocab))
    for item in txt.split():
        # get index
        xarr[vocab.index(item)] += 1
    newxs.append(xarr)

In [162]:
newxs

[array([0., 0., 0., 1., 3., 0., 2., 0., 1., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1.]),
 array([1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0.])]

In [163]:
newxstensor = torch.Tensor(newxs)

In [164]:
output = model(newxstensor)
#output.data.max(0, keepdim=True)[1]

In [165]:
output.data

tensor([[ 5.3275, -1.6307, -4.5488],
        [-2.0552, -0.3686,  1.9844],
        [ 0.4740,  0.9306, -1.4787]])

In [166]:
output.data.max(1, keepdim=False)[1]

tensor([0, 2, 1])