In [74]:
from random import *

In [5]:
import numpy as np

In [2]:
import torch

In [3]:
x = torch.rand(3, 5)

In [4]:
print(x)

tensor([[0.3875, 0.2818, 0.8161, 0.4079, 0.5021],
        [0.5409, 0.3984, 0.0790, 0.5562, 0.2066],
        [0.0469, 0.0131, 0.8942, 0.7080, 0.0885]])


In [ ]:
from os import listdir
from os.path import isfile, join, splitext
from os import walk



In [287]:
y_labels = [".cs", ".js", ".vb"]

In [ ]:
vocab = ["var","this","function","public","namespace","using","System","public", "enum", "Function", "Module"];

In [46]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random input and output data
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

# Randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

In [50]:
learning_rate = 1e-6

for t in range(500):
    # do a forward-pass by calculating predicted y
    h = x.dot(w1)
    h_relu = np.maximum(h, 0.001)
    y_pred = h_relu.dot(w2)
    
    
    #calculate loss
    loss = np.square(y_pred - y).sum()
    print(t, loss)
    
    # Backprop to compute the gradients of w1 and w2 with respect to loss
    
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)
    
    #Update Weights

    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

    
    

0 4.6478331745124025e-06
1 4.447530517778867e-06
2 4.255845253428673e-06
3 4.072434278211784e-06
4 3.896943539210209e-06
5 3.72900092271829e-06
6 3.56830330322634e-06
7 3.414562588431623e-06
8 3.26741223802107e-06
9 3.1266229295497772e-06
10 2.991889043257991e-06
11 2.862962005653955e-06
12 2.739599737948123e-06
13 2.621563087692062e-06
14 2.5085986760707127e-06
15 2.4005366409057413e-06
16 2.297109583317086e-06
17 2.1981331874125037e-06
18 2.103424161920169e-06
19 2.0128063285458044e-06
20 1.9260794202368994e-06
21 1.8430970290102803e-06
22 1.7636892923774987e-06
23 1.6877086861451022e-06
24 1.6150018486366674e-06
25 1.545423408766148e-06
26 1.4788494235533098e-06
27 1.4151392614879742e-06
28 1.3541741514242138e-06
29 1.2958391952354188e-06
30 1.2400129012028586e-06
31 1.1865931450718013e-06
32 1.1354832368060026e-06
33 1.0865735081101888e-06
34 1.0397671371666329e-06
35 9.949807649306661e-07
36 9.521188312835877e-07
37 9.111065200752832e-07
38 8.718630126171076e-07
39 8.3430714233709

452 1.0890595180309977e-14
453 1.0422854173143346e-14
454 9.975164450096885e-15
455 9.546759591952253e-15
456 9.136731149874479e-15
457 8.744343192166619e-15
458 8.368790717221496e-15
459 8.009405856847016e-15
460 7.665430483312545e-15
461 7.336204876375139e-15
462 7.021137165452892e-15
463 6.719607446481848e-15
464 6.4310191498908385e-15
465 6.154835369868072e-15
466 5.890493495907301e-15
467 5.637514997180975e-15
468 5.395431706939745e-15
469 5.163717529790208e-15
470 4.94196751041267e-15
471 4.72974095454086e-15
472 4.526614629437077e-15
473 4.3322356842270516e-15
474 4.146209246928567e-15
475 3.968163086051054e-15
476 3.7977535934024265e-15
477 3.634654785965996e-15
478 3.47857616961652e-15
479 3.3292021628186944e-15
480 3.1862476370529708e-15
481 3.049451455272467e-15
482 2.9184975563205556e-15
483 2.7931707448790844e-15
484 2.6732335940596218e-15
485 2.558452577453594e-15
486 2.4485848476451823e-15
487 2.343441687948842e-15
488 2.2428292802918252e-15
489 2.14652106260351e-15
490 

In [53]:


# Create random input and output data
x = np.random.randn(N, D_in)
y = np.random.randn(N, D_out)

# Randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

In [56]:
y

array([[-2.51711514],
       [ 0.16688039],
       [-0.44993735],
       [ 0.21578307]])

In [248]:
x = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], np.int32)
y = np.array([[0], [1], [1], [0]], np.int32)

In [249]:
for i in range(1000):
    index = (randint(0, 3))
    #print(x[index], y[index])
    x = np.append(x, [x[index]], 0)
    y = np.append(y, [y[index]], 0)

In [250]:
x.shape, y.shape

((1004, 2), (1004, 1))

In [251]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = x.shape[0], x.shape[1], 8, y.shape[1]

In [252]:
x.shape

(1004, 2)

In [253]:
N, D_in, H, D_out

(1004, 2, 8, 1)

In [254]:
# Randomly initialize weights
w1 = np.random.randn(D_in, H)
w2 = np.random.randn(H, D_out)

learning_rate = 1e-6

for t in range(100000):
    # do a forward-pass by calculating predicted y
    h = x.dot(w1)
    h_relu = np.maximum(h, 0.001)
    y_pred = h_relu.dot(w2)
    
    
    #calculate loss
    loss = np.square(y_pred - y).sum()
    if t % 10000 == 0:
        print(t, loss)
        
    if(loss < 0.005):
        break
    
    # Backprop to compute the gradients of w1 and w2 with respect to loss
    
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.T.dot(grad_y_pred)
    grad_h_relu = grad_y_pred.dot(w2.T)
    grad_h = grad_h_relu.copy()
    grad_h[h < 0] = 0
    grad_w1 = x.T.dot(grad_h)
    
    #Update Weights

    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

0 11436.743568213145
10000 0.013129347670475171
20000 0.013120795161710604
30000 0.013119824653655979
40000 0.01311885422069104
50000 0.01311788387207832
60000 0.013116913596339104
70000 0.01311594340405672
80000 0.013114973284642749
90000 0.013114003248685528


array([0., 0., 0., 0., 0., 0., 0., 0.])

In [255]:
nx = np.array([1, 0], np.int32)
h = nx.dot(w1)
h_relu = np.maximum(h, 0.001)
y_pred = h_relu.dot(w2)
y_pred

array([0.99999751])

In [267]:
model = torch.nn.Sequential(
    torch.nn.Linear(D_in, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, D_out),
)
loss_fn = torch.nn.MSELoss(reduction='sum')

In [262]:
x=torch.from_numpy(x).float()
y=torch.from_numpy(y).float()

TypeError: expected np.ndarray (got Tensor)

In [263]:
x

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        ...,
        [1., 1.],
        [1., 0.],
        [1., 1.]])

In [268]:
# Use the optim package to define an Optimizer that will update the weights of
# the model for us. Here we will use Adam; the optim package contains many other
# optimization algoriths. The first argument to the Adam constructor tells the
# optimizer which Tensors it should update.
learning_rate = 0.05
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
#optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
for t in range(500):
    # Forward pass: compute predicted y by passing x to the model.
    y_pred = model(x)

    # Compute and print loss.
    loss = loss_fn(y_pred, y)
    if t % 50 == 0:
        print(t, loss.item())

    # Before the backward pass, use the optimizer object to zero all of the
    # gradients for the variables it will update (which are the learnable
    # weights of the model). This is because by default, gradients are
    # accumulated in buffers( i.e, not overwritten) whenever .backward()
    # is called. Checkout docs of torch.autograd.backward for more details.
    optimizer.zero_grad()

    # Backward pass: compute gradient of the loss with respect to model
    # parameters
    loss.backward()

    # Calling the step function on an Optimizer makes an update to its
    # parameters
    optimizer.step()

0 255.3799285888672
50 0.09982776641845703
100 0.0018633328145369887
150 4.7891412577882875e-06
200 5.258366542193471e-08
250 9.426928682110258e-11
300 3.992028929644675e-12
350 1.861288900784075e-12
400 4.674954867667225e-12
450 4.665295927352986e-12


In [270]:
[m for m in model.parameters()]

[Parameter containing:
 tensor([[ 0.3146, -0.0017],
         [-0.9313,  0.6113],
         [-0.7127,  0.1330],
         [-0.5999, -0.2080],
         [-0.3640, -0.6911],
         [-0.9767,  0.6422],
         [-0.6464,  0.7695],
         [ 1.0095, -1.4238]], requires_grad=True), Parameter containing:
 tensor([-0.0840, -0.1136, -0.1698,  0.1986, -0.3879, -0.1708, -0.2216, -0.2337],
        requires_grad=True), Parameter containing:
 tensor([[-0.2523,  0.5793, -0.1111, -0.2907,  0.2884,  0.7567,  0.5424,  1.2895]],
        requires_grad=True), Parameter containing:
 tensor([0.0577], requires_grad=True)]

In [272]:
nx = torch.from_numpy(np.array([0, 1], np.int32)).float()
y_pred = model(nx)
round(y_pred.item(), 3)

1.0

In [273]:
x

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        ...,
        [1., 1.],
        [1., 0.],
        [1., 1.]])

In [289]:
at = torch.arange(0,len(y_labels))

In [290]:
y_labels

['.cs', '.js', '.vb']

In [292]:
pY = torch.zeros(len(at), at.max()+1).scatter_(1, at.unsqueeze(1), 1.)

## Let's do cross entropy exercise

In [297]:
pY[0]

tensor([1., 0., 0.])

In [305]:
import numpy as np

# do one hot encoding
# 0 : 1 0 0
# 1 : 0 1 0
# 2 : 0 0 1

Y = np.array([0, 0, 1])

Y_pred1 = np.array([0.2, 0.2, 0.7])
Y_pred2 = np.array([0.1, 0.3, 0.10])

(-Y * np.log(Y_pred1)), (-Y * np.log(Y_pred2))

(array([-0.        , -0.        ,  0.35667494]),
 array([-0.        , -0.        ,  2.30258509]))

In [308]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable

In [315]:
# let's do it in pytorch

loss = torch.nn.CrossEntropyLoss()

In [329]:
Y = Variable(torch.LongTensor([0]), requires_grad=False)

# input is of size nBatch x nClasses = 1 x 4
# Y_pred are logits (not softmax)
Y_pred1 = Variable(torch.Tensor([[2.0, 1.0, 0.1]]))
Y_pred2 = Variable(torch.Tensor([[0.5, 2.0, 0.3]]))

l1 = loss(Y_pred1, Y)
l2 = loss(Y_pred2, Y)

print("PyTorch Loss1 = ", l1.data, "\nPyTorch Loss2=", l2.data)

PyTorch Loss1 =  tensor(0.4170) 
PyTorch Loss2= tensor(1.8406)


In [330]:
# target is of size nBatch
# each element in target has to have 0 <= value < nClasses (0-2)
# Input is class, not one-hot
Y = Variable(torch.LongTensor([2, 0, 1]), requires_grad=False)

# input is of size nBatch x nClasses = 2 x 4
# Y_pred are logits (not softmax)
Y_pred1 = Variable(torch.Tensor([[0.1, 0.2, 0.9],
                                 [1.1, 0.1, 0.2],
                                 [0.2, 2.1, 0.1]]))


Y_pred2 = Variable(torch.Tensor([[0.8, 0.2, 0.3],
                                 [0.2, 0.3, 0.5],
                                 [0.2, 0.2, 0.5]]))

l1 = loss(Y_pred1, Y)
l2 = loss(Y_pred2, Y)

print("Batch Loss1 = ", l1.data, "\nBatch Loss2=", l2.data)

Batch Loss1 =  tensor(0.4966) 
Batch Loss2= tensor(1.2389)
